In [1]:
import numpy as np

In [11]:
def filterCoord_1(x, y, z, val, minvals, maxvals):
    filtered_x = []
    filtered_y = []
    filtered_z = []
    filtered_val = []
    
    for x_val, y_val, z_val, v in zip(x, y, z, val):
        if minvals[0] <= x_val <= maxvals[0] and minvals[1] <= y_val <= maxvals[1] and minvals[2] <= z_val:
            filtered_x.append(x_val)
            filtered_y.append(y_val)
            filtered_z.append(z_val)
            filtered_val.append(v)
    return np.array([filtered_x, filtered_y, filtered_z, filtered_val])

import numpy as np

def filterCoord(x, y, z, val, minvals, maxvals):
    # Convert input lists to NumPy arrays
    x = np.array(x)
    y = np.array(y)
    z = np.array(z)
    val = np.array(val)

    # Define masks for filtering
    x_mask = (minvals[0] <= x) & (x <= maxvals[0])
    y_mask = (minvals[1] <= y) & (y <= maxvals[1])
    z_mask = (minvals[2] <= z)

    # Combine the masks to get the final filtering mask
    final_mask = x_mask & y_mask & z_mask

    # Use the filtering mask to get the filtered arrays
    filtered_x = x[final_mask]
    filtered_y = y[final_mask]
    filtered_z = z[final_mask]
    filtered_val = val[final_mask]
    return np.array([filtered_x, filtered_y, filtered_z, filtered_val])


In [16]:
N = 100
DriftedEvt = np.array( [[2,2] for i in range(N)] + [1,2,3], [1,3,3], [1,3,3], [1,3,3], [5,5,5], [10,10,10],  [10,10,10], [2,4,6], [2,6,5], [10,10,10],  [10,10,10],  [10,10,10], [10,20,14], [2,20,15], [2,10,9]])

DriftedEvtGrid = np.stack(DriftedEvt, axis=-1)
minvals = np.array([DriftedEvtGrid[0].min()+5, DriftedEvtGrid[1].min(), DriftedEvtGrid[2].min()])
maxvals = np.array([DriftedEvtGrid[0].max()+5, DriftedEvtGrid[1].max(), DriftedEvtGrid[2].max()])

print(minvals, maxvals)


[6 2 3] [15 20 15]
(15,)


In [22]:

x, y, z = DriftedEvtGrid
print(DriftedEvtGrid)
val = 2*z

%timeit filtered_coord = filterCoord(x, y, z, val, minvals, maxvals )
%timeit filtered_coord = filterCoord_1(x, y, z, val, minvals, maxvals )
print(filtered_coord)

[[ 1  1  1  1  5 10 10  2  2 10 10 10 10  2  2]
 [ 2  3  3  3  5 10 10  4  6 10 10 10 20 20 10]
 [ 3  3  3  3  5 10 10  6  5 10 10 10 14 15  9]]
9.11 µs ± 97.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
6.9 µs ± 42.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
[[10 10 10 10 10 10]
 [10 10 10 10 10 20]
 [10 10 10 10 10 14]
 [20 20 20 20 20 28]]
