In [1]:
import numpy as np

def generate_random_coordinates(N):
    # Generate random [x, y, z] coordinates
    x = np.random.rand(N)
    y = np.random.rand(N)
    z = np.random.rand(N)

    # Combine x, y, z coordinates into a single array
    coordinates = np.column_stack((x, y, z))

    return coordinates


In [3]:

N = 100  # Replace 10 with the desired length
k = 100

random_coordinates = generate_random_coordinates(N)*k
print(random_coordinates)


[[66.79635191 61.41835679 32.25614175]
 [73.39195446 42.26971955 40.21909488]
 [ 6.78094645 79.88261427 54.84473907]
 [82.44084035 38.06540605 92.34511417]
 [ 7.63292751 73.10431971 55.65777455]
 [41.67644198 92.30349226 92.53538744]
 [54.16891053 45.52404064 38.43469984]
 [17.40769808 21.55936186 96.3285995 ]
 [31.72326693 80.22893968 62.36438682]
 [33.84272949 13.74105655 94.56884338]
 [50.24780562 72.07827522 44.14117865]
 [45.56831758 60.47188613  6.68008253]
 [39.77181715 50.57243467 53.89139908]
 [78.05072183 69.05768194 47.92384613]
 [ 6.43956364 31.94688559 39.91703725]
 [27.96245786 16.00454674 52.150657  ]
 [79.4839095  27.03690614  1.27851807]
 [39.41036841 13.13295197 30.58368347]
 [75.34414846 59.84688105 64.10703361]
 [81.60277315 35.8389062   4.28954082]
 [43.1422257  48.23977403 42.7252063 ]
 [24.9615317  10.79861953 35.13684009]
 [82.07452245 23.53247312 75.75800296]
 [ 2.01972342 31.57786684 60.69529582]
 [27.05844606 44.99656932 44.95259311]
 [93.78875996 48.85118489